name: Build Test

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Makefile'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'src/**'
      - 'Makefile'
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        default: '3.10'
        type: choice
        options:
          - '3.10'
          - '3.11'
          - '3.12'

jobs:
  build:
    name: make install with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          auto-update-conda: true
          channels: conda-forge
          mamba-version: "*"
          python-version: ${{ matrix.python-version }}

      - run: |
          make install PYTHON_VERSION=${{ matrix.python-version }}
        shell: bash -el {0}